import {
  generateNonExtractableIdentity,
  type HpkeIdentity,
} from './auth-hpke';

const STORE_NAME = 'identities';
const RECORD_ID = 'primary-hpke-auth-v1';

/** Persists a non-extractable WebCrypto identity by IndexedDB structured clone. */
export class IndexedDbIdentityStore {
  constructor(private readonly databaseName = 'syncnotifications-crypto-v1') {}

  async loadOrCreate(): Promise<HpkeIdentity> {
    const database = await this.openDatabase();
    try {
      const readTransaction = database.transaction(STORE_NAME, 'readonly');
      const readCompleted = transactionCompleted(readTransaction);
      const existing = await requestResult<HpkeIdentity | undefined>(
        readTransaction.objectStore(STORE_NAME).get(RECORD_ID),
      );
      await readCompleted;
      if (existing !== undefined) {
        validateIdentity(existing);
        return existing;
      }

      const generated = await generateNonExtractableIdentity();
      // A read/write transaction serializes competing creators. Recheck inside
      // it so no caller silently overwrites an identity generated by another.
      const transaction = database.transaction(STORE_NAME, 'readwrite');
      const completed = transactionCompleted(transaction);
      const store = transaction.objectStore(STORE_NAME);
      const concurrentlyCreated = await requestResult<HpkeIdentity | undefined>(
        store.get(RECORD_ID),
      );
      if (concurrentlyCreated !== undefined) {
        await completed;
        validateIdentity(concurrentlyCreated);
        return concurrentlyCreated;
      }

      await requestResult(store.add(generated, RECORD_ID));
      await completed;
      validateIdentity(generated);
      return generated;
    } finally {
      database.close();
    }
  }

  async clear(): Promise<void> {
    const database = await this.openDatabase();
    try {
      const transaction = database.transaction(STORE_NAME, 'readwrite');
      const completed = transactionCompleted(transaction);
      await requestResult(transaction.objectStore(STORE_NAME).delete(RECORD_ID));
      await completed;
    } finally {
      database.close();
    }
  }

  private openDatabase(): Promise<IDBDatabase> {
    return new Promise((resolve, reject) => {
      const request = indexedDB.open(this.databaseName, 1);
      request.onupgradeneeded = () => {
        if (!request.result.objectStoreNames.contains(STORE_NAME)) {
          request.result.createObjectStore(STORE_NAME);
        }
      };
      request.onsuccess = () => resolve(request.result);
      request.onerror = () => reject(request.error ?? new Error('Failed to open identity database'));
      request.onblocked = () => reject(new Error('Identity database upgrade was blocked'));
    });
  }
}

function validateIdentity(identity: HpkeIdentity): void {
  const algorithm = identity.privateKey.algorithm as EcKeyAlgorithm;
  if (
    identity.privateKey.type !== 'private' ||
    identity.privateKey.extractable ||
    algorithm.name !== 'ECDH' ||
    algorithm.namedCurve !== 'P-256' ||
    !identity.privateKey.usages.includes('deriveBits')
  ) {
    throw new Error('Stored HPKE identity does not meet non-extractable P-256 policy');
  }
  if (identity.publicKey.type !== 'public') {
    throw new Error('Stored HPKE identity public key is invalid');
  }
}

function requestResult<T>(request: IDBRequest<T>): Promise<T> {
  return new Promise((resolve, reject) => {
    request.onsuccess = () => resolve(request.result);
    request.onerror = () => reject(request.error ?? new Error('IndexedDB request failed'));
  });
}

function transactionCompleted(transaction: IDBTransaction): Promise<void> {
  return new Promise((resolve, reject) => {
    transaction.oncomplete = () => resolve();
    transaction.onabort = () => reject(transaction.error ?? new Error('IndexedDB transaction aborted'));
    transaction.onerror = () => reject(transaction.error ?? new Error('IndexedDB transaction failed'));
  });
}
