import {
  generateNonExtractableIdentity,
  serializeIdentityPublicKey,
  type HpkeIdentity,
} from './auth-hpke';

const STORE_NAME = 'identities';
const RECORD_ID = 'primary-hpke-auth-v1';
const RECORD_FORMAT_VERSION = 1;

interface IdentityRotationRecord {
  formatVersion: number;
  current: HpkeIdentity;
  pending?: HpkeIdentity;
}

export interface StoredIdentityRotation {
  current: HpkeIdentity;
  pending: HpkeIdentity;
}

type StoredIdentityRecord = HpkeIdentity | IdentityRotationRecord;

/** Persists current and at most one pending non-extractable WebCrypto identity. */
export class IndexedDbIdentityStore {
  constructor(private readonly databaseName = 'syncnotifications-crypto-v1') {}

  async loadExisting(): Promise<HpkeIdentity | undefined> {
    return (await this.loadState())?.current;
  }

  async loadRotation(): Promise<StoredIdentityRotation | undefined> {
    const state = await this.loadState();
    if (state?.pending === undefined) return undefined;
    return { current: state.current, pending: state.pending };
  }

  async loadOrCreate(): Promise<HpkeIdentity> {
    const existing = await this.loadExisting();
    if (existing !== undefined) return existing;

    const generated = await generateNonExtractableIdentity();
    const database = await this.openDatabase();
    try {
      // A read/write transaction serializes competing creators. Recheck inside
      // it so no caller silently overwrites an identity generated by another.
      const transaction = database.transaction(STORE_NAME, 'readwrite');
      const completed = transactionCompleted(transaction);
      const store = transaction.objectStore(STORE_NAME);
      const concurrentlyCreated = await requestResult<StoredIdentityRecord | undefined>(
        store.get(RECORD_ID),
      );
      if (concurrentlyCreated !== undefined) {
        await completed;
        return (await normalizeAndValidateRecord(concurrentlyCreated)).current;
      }

      await requestResult(store.add(generated, RECORD_ID));
      await completed;
      validateIdentity(generated);
      return generated;
    } finally {
      database.close();
    }
  }

  /** Creates one pending identity without replacing current; reconstruction reuses it exactly. */
  async prepareRotation(): Promise<StoredIdentityRotation> {
    const existing = await this.loadState();
    if (existing === undefined) throw new Error('HPKE identity is not configured');
    if (existing.pending !== undefined) {
      return { current: existing.current, pending: existing.pending };
    }

    const generated = await generateNonExtractableIdentity();
    validateIdentity(generated);
    if (await identitiesEqual(existing.current, generated)) {
      throw new Error('Pending HPKE identity must differ from current');
    }

    const database = await this.openDatabase();
    try {
      const transaction = database.transaction(STORE_NAME, 'readwrite');
      const completed = transactionCompleted(transaction);
      const store = transaction.objectStore(STORE_NAME);
      const stored = await requestResult<StoredIdentityRecord | undefined>(store.get(RECORD_ID));
      if (stored === undefined) {
        transaction.abort();
        await completed.catch(() => undefined);
        throw new Error('HPKE identity is not configured');
      }
      const state = normalizeRecord(stored);
      validateIdentity(state.current);
      if (state.pending !== undefined) {
        await completed;
        const validated = await validateRotationState(state);
        return { current: validated.current, pending: validated.pending! };
      }
      await requestResult(store.put({
        formatVersion: RECORD_FORMAT_VERSION,
        current: state.current,
        pending: generated,
      } satisfies IdentityRotationRecord, RECORD_ID));
      await completed;
      return { current: state.current, pending: generated };
    } finally {
      database.close();
    }
  }

  async clear(): Promise<void> {
    const database = await this.openDatabase();
    try {
      const transaction = database.transaction(STORE_NAME, 'readwrite');
      const completed = transactionCompleted(transaction);
      await requestResult(transaction.objectStore(STORE_NAME).delete(RECORD_ID));
      await completed;
    } finally {
      database.close();
    }
  }

  private async loadState(): Promise<IdentityRotationRecord | undefined> {
    const database = await this.openDatabase();
    try {
      const transaction = database.transaction(STORE_NAME, 'readonly');
      const completed = transactionCompleted(transaction);
      const stored = await requestResult<StoredIdentityRecord | undefined>(
        transaction.objectStore(STORE_NAME).get(RECORD_ID),
      );
      await completed;
      return stored === undefined ? undefined : normalizeAndValidateRecord(stored);
    } finally {
      database.close();
    }
  }

  private openDatabase(): Promise<IDBDatabase> {
    return new Promise((resolve, reject) => {
      const request = indexedDB.open(this.databaseName, 1);
      request.onupgradeneeded = () => {
        if (!request.result.objectStoreNames.contains(STORE_NAME)) {
          request.result.createObjectStore(STORE_NAME);
        }
      };
      request.onsuccess = () => resolve(request.result);
      request.onerror = () => reject(request.error ?? new Error('Failed to open identity database'));
      request.onblocked = () => reject(new Error('Identity database upgrade was blocked'));
    });
  }
}

function normalizeRecord(stored: StoredIdentityRecord): IdentityRotationRecord {
  if ('current' in stored) {
    if (stored.formatVersion !== RECORD_FORMAT_VERSION) {
      throw new Error('Stored HPKE identity record version is unsupported');
    }
    return stored;
  }
  return { formatVersion: RECORD_FORMAT_VERSION, current: stored };
}

async function normalizeAndValidateRecord(
  stored: StoredIdentityRecord,
): Promise<IdentityRotationRecord> {
  return validateRotationState(normalizeRecord(stored));
}

async function validateRotationState(state: IdentityRotationRecord): Promise<IdentityRotationRecord> {
  validateIdentity(state.current);
  if (state.pending !== undefined) {
    validateIdentity(state.pending);
    if (await identitiesEqual(state.current, state.pending)) {
      throw new Error('Pending HPKE identity must differ from current');
    }
  }
  return state;
}

async function identitiesEqual(left: HpkeIdentity, right: HpkeIdentity): Promise<boolean> {
  const leftPublic = await serializeIdentityPublicKey(left);
  const rightPublic = await serializeIdentityPublicKey(right);
  return leftPublic.byteLength === rightPublic.byteLength &&
    leftPublic.every((value, index) => value === rightPublic[index]);
}

function validateIdentity(identity: HpkeIdentity): void {
  const algorithm = identity.privateKey.algorithm as EcKeyAlgorithm;
  if (
    identity.privateKey.type !== 'private' ||
    identity.privateKey.extractable ||
    algorithm.name !== 'ECDH' ||
    algorithm.namedCurve !== 'P-256' ||
    !identity.privateKey.usages.includes('deriveBits')
  ) {
    throw new Error('Stored HPKE identity does not meet non-extractable P-256 policy');
  }
  if (identity.publicKey.type !== 'public') {
    throw new Error('Stored HPKE identity public key is invalid');
  }
}

function requestResult<T>(request: IDBRequest<T>): Promise<T> {
  return new Promise((resolve, reject) => {
    request.onsuccess = () => resolve(request.result);
    request.onerror = () => reject(request.error ?? new Error('IndexedDB request failed'));
  });
}

function transactionCompleted(transaction: IDBTransaction): Promise<void> {
  return new Promise((resolve, reject) => {
    transaction.oncomplete = () => resolve();
    transaction.onabort = () => reject(transaction.error ?? new Error('IndexedDB transaction aborted'));
    transaction.onerror = () => reject(transaction.error ?? new Error('IndexedDB transaction failed'));
  });
}
